### ISSUE TITLE
I can not user this plugin with WP REST Filter plugin(Error below)

### ISSUE THREAD

**Issue by chrisgate** [SK8-PTY-LTD/wp-rest-user#1]
I got below when trying to user this plugin along with WP REST Filter plugin.

NAME_VERSION already defined in ......\wp-content\plugins\wp-rest-user\wp-rest-user.php on line 38

Thanks

**Comment by jacktator** [comment]
seem to,work fine on our end. Which version are you using?

WP: 4.X?
WPRESTFilter: ?
WPRESTUser: ?

**Comment by chrisgate** [comment]
WP:4.9.7 latest
WPRESTFilter: 1.2.4
WPRESTUser: 1.3.2

Thanks for your reply

**Comment by chrisgate** [comment]
This is additional error  : 
The plugin generated 229 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

**Comment by chrisgate** [comment]
any luck with me?

**Comment by jacktator** [comment]
@chrisgate please email us the login to your site via support@sk8.tech, we'll have a closer look.

**Comment by jacktator** [comment]
@chrisgate Hi, we got your email. This had been fixed. We'll release an update on WordPress.org soon this afternoon.

**Comment by chrisgate** [comment]
@jacktator Thanks ...........its okay now
