### ISSUE TITLE
Username field 'username' is required

### ISSUE THREAD

**Issue by fitzmode** [SK8-PTY-LTD/wp-rest-user#4]
Hi there, great work you've done here. I get a code 400 error when I post the user credentials to register the user. My JSON payload is as below
```
{
"username": "fitz",
"email": "anotheremail@gmail.com",
"password:"somepassword"
}
```
And the response I get.

```
{
    "code": 400,
    "message": "Username field 'username' is required.",
    "data": {
        "status": 400
    }
}
```

**Comment by anesumuz** [comment]
After a bit of investigation, it seems the `$parameter` value is null in `public/class-wp-rest-user-puclic.php`.

**Comment by jacktator** [comment]
@anesumuz We'll check it our asap.

**Comment by borosuman** [comment]
Hi @anesumuz , I was facing the same problem on my site running on Wordpress 4.9.8. I solved this by modifying the `register_user` function as below:
```
public function register_user(WP_REST_Request $request) {
                $response = array();
		$username = $request['username'];
		$email = $request['email'];
		$password = $request['password'];
		$role = $request['role'];

		$username = sanitize_text_field($username);
		$email = sanitize_text_field($email);
		$password = sanitize_text_field($password);
		$role = sanitize_text_field($role);
		$error = new WP_Error();
                //Rest are same as original
}
```

**Comment by anesumuz** [comment]
@borosuman thanks for the tip, let me have a crack at that and revert.

**Comment by joshuaiz** [comment]
Thanks for this plugin.

Any reason why this was closed and a PR was not made? Still getting this issue, even with changing the `register_user` function as @borosuman suggested. 

Can this get a fix so we don't have to hack plugin code?

**Comment by rocifier** [comment]
This is working for me. What exact path are you sending a POST to for the registration? It should be `/wp-json/wp/v2/users/register`. And are you setting `content-type: application/json` in your header?

**Comment by joshuaiz** [comment]
@rocifier my bad. Had to set the `content-type: application/json` - that was it. I know the docs say JSON body but maybe point this out as it is not the default.

**Comment by jacktator** [comment]
I've added it to README
