### ISSUE TITLE
No email send after forgot password call

### ISSUE THREAD

**Issue by Cy0u** [SK8-PTY-LTD/wp-rest-user#5]
After calling the api with the correct JSON my repsonse return a success.
The postman also said: `
{
    "code": 200,
    "message": "Reset Password link had been send to your email."
}`
There where no email send to the email adress called in the post request.
Some ideas ?
Thanks and best regards.

**Comment by giam87** [comment]
Same problem.

**Comment by taeo920** [comment]
Same issue. It looks like the lost_password function is calling

do_action('retrieve_password', $user_login);

But there is no action defined for the key "retrieve_password" in the plugin or WordPress core. There is a "retrieve_password" function in WP core but it has no action associated with it and does not accept any arguments.

**Comment by giam87** [comment]
I solved with custom function

 $user = get_user_by('email', $user_login);
 $key = get_password_reset_key( $user );

then with wp_mail() send reset link to user email

$rp_link = '<a href="' . site_url()."/wp-login.php?action=rp&key=$key&login=" . rawurlencode($user_lg) . '">' . site_url()."/wp-login.php?action=rp&key=$key&login=" . rawurlencode($user_lg) . '</a>';

**Comment by taeo920** [comment]
Thank you, I was just about to patch this myself as well.

**Comment by chrisgate** [comment]
@giam87 where are we going to put those....can u consider steps to take.

thanks anticipations.

**Comment by Cy0u** [comment]
I also tried to do custom functions ... I finished with "I don't have enough knowledge of this sh*t" :D

I will give them a try on monday ... thanks for your help and work ... I appreciate :-)

**Comment by sviluppomania** [comment]
https://github.com/SK8-PTY-LTD/wp-rest-user/pull/7
