### ISSUE TITLE
Any preview of adding more functions?

### ISSUE THREAD

**Issue by Jabelriera** [SK8-PTY-LTD/wp-rest-user#6]
Is there any preview of adding more functions? I was thinking on:

- Login

- Change Password

- Get User 

Thank you!

**Comment by jacktator** [comment]
@Jabelriera Thank you for your enthusiasm,

1. Login had already been implemented by other plugin, E.g. JWT Token.
2. Change Password is a great idea. However enabling such would mean that anyone would be able to change password via REST API, which does not sound secure. 
3. Get User is already implemented in the WP Core REST API.
